### ISSUE TITLE
[REGRESSION] Reflection outputs duplicate properties, causes MySQL Migration Failures

### ISSUE THREAD

**Issue by jseibert** [vapor/core#119]
Let's say you have a model like so:

```swift
final class Account: MySQLModel, Migration, Content, Parameter {
    var id: Int?
    var authId: UUID
    
    var status: Status = .provisioned
    enum Status: Int, Codable, MySQLDataConvertible, MySQLColumnDefinitionStaticRepresentable {
        public static var mySQLColumnDefinition = MySQLColumnDefinition.tinyInt()
        
        case provisioned = 0
        case activated = 1
        case verified = 2
    }
}
```

The auto-generated migration fails with `MySQL.MySQLErrorPacket(errorCode: 1060, sqlStateMarker: Optional("#"), sqlState: Optional("42S21"), errorMessage: "Duplicate column name \'status\'"))`

Digging into it, it's because Reflection is outputting duplicate properties for the Status field. Printing the list of generated properties yields:
```
[
  id: Optional<Int>, 
  authId: UUID, 
  status: Status, 
  status: Int
]
```

**Comment by jseibert** [comment]
This worked correctly in 3.0.0-rc.2.3

**Comment by jseibert** [comment]
Interesting. It works if you conform the enum to `ReflectionDecodable`. This is non-obvious.

**Comment by tanner0101** [comment]
Ideally the enum should be `ReflectionDecodable`. When MySQL 3.0.0 is tagged it will be getting a `MySQLEnum` protocol to help with creating compatible enums (SQLite and PSQL, too). This will include a test to ensure that enums are working properly with Fluent (including migrations).

Track here: https://github.com/vapor/fluent-mysql/issues/99

That being said, this should not yield two properties. I think the problem here is that [this code](https://github.com/vapor/core/blob/master/Sources/Core/CodableReflection/ReflectionDecoders.swift#L142-L147) should only execute if the type is reflection decodable.

I will take a look at this one, thanks for reporting.
