### ISSUE TITLE
DirectoryConfig.workDir not working with Xcode 11 integration with SPM

### ISSUE THREAD

**Issue by 0xTim** [vapor/core#207]
In Xcode 11, if you open the Package.swift file directly (to get a new Xcode 11 Swift Package project) uses of `DirectoryConfig.workDir` fail, probably due to DerviedData being in a new place. This breaks `.env` and Leaf etc.

Current workaround - use `swift package generate-xcodeproj` and use the generated project

**Comment by 0xTim** [comment]
Relevant https://github.com/apple/swift-package-manager/blob/master/Sources/TestSupport/Resources.swift#L51

**Comment by tanner0101** [comment]
This is a tricky one to solve. It looks like Xcode 11 w/ SPM is using a #`file` path in the system DerivedData. This path has no correlation to where the source code is for the actual project, so the hacks we have in place currently for automatic detection no longer work.

I think the best solution here is to rely on setting a "Custom Working Directory" in the scheme. 

![Screen Shot 2019-06-11 at 4 06 33 PM](https://user-images.githubusercontent.com/1342803/59302875-f82ea180-8c62-11e9-983b-3c00888789a0.png)

Since Xcode 11 SPM settings are now persisted in the `.swiftpm` folder, you only need to set this option once. 

For Vapor 4, this can be the default behavior of `DirectoryConfiguration.detect()` since Xcode 11 will be required. 

For Vapor 3, we will need some logic to skip the current `#file` hacks when Xcode 11 is being used, but continue to use the hacks with Xcode 10. The resulting file path in Xcode 11 contains `SourcePackages/checkouts` which I believe should be unique enough to successfully determine whether we are in Xcode 11 or 10. 

I'll put up a PR now w/ this fix and we can test it out.

**Comment by tanner0101** [comment]
PR here: https://github.com/vapor/core/pull/208

**Comment by Yasumoto** [comment]
I didn’t think of this immediately, so just leaving it for folks as a temporary workaround: in the meantime I’m just using `swift run` from terminal while using Xcode 11 for editing (and of course, SPM support!)

**Comment by tanner0101** [comment]
Another workaround is to register a custom `DirectoryConfig` only in Xcode:

```swift
#if Xcode
services.register { container in
    return DirectoryConfig(workDir: "/path/to/package")
}
#endif
```

**Comment by 0xTim** [comment]
(Workaround doesn't scale when working across teams/computers for those wondering)

**Comment by tonyarnold** [comment]
I'm not sure if this is helpful at all, but the following implementation scales moreso than the previous example. It still requires that the users set the working directory manually under the Xcode scheme options:

```swift
#if Xcode
services.register { container in
    return DirectoryConfig(workDir: Process().currentDirectoryPath)
}
#if
```

Does Xcode pass environment variables like `SRCROOT` and friends to the executable it's about to debug/run?

**Comment by patchthecode** [comment]
Can you guys allow us to send any args to a vapor app on launch.
Currently you disallow this and only allow approved ones.

If you allow this, vapor app can be more flexible.
I can send in what ever parameter i want including a workingDir variable, or in my case, a lot of other custom configs. The Environment variable thing is a hassle for me.

bad idea?

**Comment by eriadam** [comment]
> (Workaround doesn't scale when working across teams/computers for those wondering)

How about adding an environment variable?

```
DirectoryConfiguration(workingDirectory: Environment.get("WORKING_DIRECTORY"))
```

**Comment by 0xTim** [comment]
You'd still need to set it per project per user. Ideally you can checkout your code and just build and run - unfortunately SwiftPM doesn't work quite like that yet
